version: '3.7'  # Specify the version of the Compose file

services:
  order.api:
    image: orderapi
    build:
      context: .
      dockerfile: OrderService/Order.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MSSQL_DATABASE=OrdersDB
      - MSSQL_HOST=sqlserver
      - MSSQL_PORT=1433
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=Password!
      - RabbitMQ_HostName=rabbitmq
      - RabbitMQ_UserName=user
      - RabbitMQ_Password=password
      - RabbitMQ_Port=5672
      - RabbitMQ_Products_Exchange=product.exchange
      - ClientMicroserviceName=client.api
      - ClientMicroservicePort=8081
      - ClientMicroserviceExternalName=localhost
      - ClientMicroserviceExternalPort=5002
    ports:
      - "5001:8080"  # This maps the external port 5001 to internal port 8080
    depends_on:
      - sqlserver
    networks:
      - orders_network
 
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - orders_network

  client.api:
    image: clientapi
    build:
      context: .
      dockerfile: ClientService/Client.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
      - RabbitMQ_HostName=rabbitmq
      - RabbitMQ_UserName=user
      - RabbitMQ_Password=password
      - RabbitMQ_Port=5672
      - RabbitMQ_Products_Exchange=product.exchange
      - OrdersMicroserviceName=order.api
      - OrdersMicroservicePort=8080
      - ProductsMicroserviceName=product.api
      - ProductsMicroservicePort=8083
      - OrdersMicroserviceExternalName=localhost
      - OrdersMicroserviceExternalPort=5001
    ports:
      - "5002:8081"  # Mapping external port 5002 to internal port 8081
    depends_on:
      - order.api
    networks:
      - orders_network 

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - orders_network

  product.api:
    image: productapi
    build:
      context: .
      dockerfile: ProductService/Product.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8083
      - MSSQL_DATABASE=ProductsDB
      - MSSQL_HOST=sqlserver
      - MSSQL_PORT=1433
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=Password!
      - RabbitMQ_HostName=rabbitmq
      - RabbitMQ_UserName=user
      - RabbitMQ_Password=password
      - RabbitMQ_Port=5672
      - RabbitMQ_Products_Exchange=product.exchange
      - OrdersMicroserviceName=order.api
      - OrdersMicroservicePort=8080
    ports:
      - "127.0.0.1:5003:8083"
    depends_on:
      - sqlserver
    networks:
      - orders_network

networks:
  orders_network:  # Define the custom network
